### ISSUE TITLE
After computer restarts, Windows Defender becomes enabled again.

### ISSUE THREAD

**Issue by gitercn** [qtkite/defender-control#4] opened 2021-11-27 02:59 UTC
Hi, I'm using Windows 11 21H2. It can disable Windows Defender and works well.
But after the computer restarts, the Windows Defender becomes enabled again. So I need to run it after reboot.
Could you make it permanently disable the Windows Defender?

**Comment by qtkite** [comment] 2021-11-27 03:34
Thanks for letting me know - I currently don't have any up to date Windows 11 installed on any of my machines right now, but I'll take a look when I get the chance

**Comment by totalgaara** [comment] 2021-11-27 08:36
I can confirm this issue, unfortunatly Windows Defender seems to auto-re enable himself, the pain monster is back..

**Comment by dzmitry-lahoda** [comment] 2021-12-02 08:30
wow. seem need to install windows from iso where it was deleted. but usually people delete other useful stuff. on my machine defender starts crushing my pc during compilation for some reason, so it slow down it really. i hate it. and not way to disable it on 11. 
if 11 will be fixed, will donate 25 USD for that feature.

**Comment by qtkite** [comment] 2021-12-05 13:29
> I can confirm this issue, unfortunatly Windows Defender seems to auto-re enable himself, the pain monster is back..

I'm having trouble reproducing. I am currently on 21H2. Are you using a preview build?

**Comment by gitercn** [comment] 2021-12-05 15:06
> > I can confirm this issue, unfortunatly Windows Defender seems to auto-re enable himself, the pain monster is back..
> 
> I'm having trouble reproducing. I am currently on 21H2. Are you using a preview build? Do you have riot vanguard running?

I'm not using a preview build. I don't have riot vanguard running. 
I'm using this version (ed2k://|file|zh-cn_windows_11_business_editions_x64_dvd_f5f6bcbd.iso|5413181440|88CA1AE28F5F8A238647561B5C00E511|/). I used rufus to write the iso image to usb drive. Then I formatted my computer's disk and freshly installed Windows 11.

**Comment by qtkite** [comment] 2022-01-07 06:50
Okay I finally been able to replicate it, seems to be a delay when it happens. Might need to look into adding something that runs the program on boot or figuring out why it happens

**Comment by ENDERM4NQ** [comment] 2022-01-10 01:53
> Hi, I'm using Windows 11 21H2. It can disable Windows Defender and works well. But after the computer restarts, the Windows Defender becomes enabled again. So I need to run it after reboot. Could you make it permanently disable the Windows Defender?

As a quick fix u can drop disable windows defender exe to startup and load it on every boot this will save u time running it manualy but as I said thats just quick fix u can do your self

**Comment by qtkite** [comment] 2022-01-25 11:31
Windows 11 should be supported now.

**Closed by qtkite** 2022-01-25 11:31 UTC
